-- =============================================
-- TABLE: tags
-- Description: User-created tags for organizing items
-- Status: ✅ DEPLOYED (MVP)
-- =============================================

CREATE TABLE tags (
    -- Primary Key
    tag_id INT IDENTITY(1,1) PRIMARY KEY,

    -- Owner
    user_id INT NOT NULL,

    -- Tag info
    name NVARCHAR(255) NOT NULL,
    slug NVARCHAR(255) NOT NULL, -- Generated by trigger
    color NVARCHAR(7) NULL DEFAULT '#3B82F6', -- Hex color (e.g., #3B82F6)
    icon NVARCHAR(50) NULL, -- Icon name or emoji
    description NVARCHAR(1000) NULL,

    -- Metadata
    metadata NVARCHAR(MAX) NULL, -- JSON: additional properties
    usage_count INT NOT NULL DEFAULT 0, -- Number of items using this tag

    -- Timestamps
    created_at DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    updated_at DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    deleted_at DATETIME2 NULL, -- Soft delete

    -- Foreign Keys
    CONSTRAINT FK_tags_user FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    -- Unique Constraints
    CONSTRAINT UQ_tags_user_slug UNIQUE (user_id, slug)
);

-- =============================================
-- INDEXES
-- =============================================

-- Index for user's tags
CREATE NONCLUSTERED INDEX IX_tags_user_id
    ON tags(user_id)
    WHERE deleted_at IS NULL;

-- Index for searching by name
CREATE NONCLUSTERED INDEX IX_tags_name
    ON tags(user_id, name)
    WHERE deleted_at IS NULL;

-- Index for sorting by usage
CREATE NONCLUSTERED INDEX IX_tags_usage
    ON tags(user_id, usage_count DESC)
    WHERE deleted_at IS NULL;

-- =============================================
-- NOTES
-- =============================================
-- - Slug is auto-generated by trigger TR_tags_generate_slug
-- - Slug is nullable initially, populated after INSERT
-- - usage_count is updated when tags are added/removed from items
-- - Each user can have multiple tags with unique slugs
