-- Manual script to fix the duplicate UserId columns issue
-- This script removes the duplicate foreign key columns generated by conflicting EF Core relationships

-- Drop foreign key constraints first
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_notes_users_UserId1')
BEGIN
    ALTER TABLE notes DROP CONSTRAINT FK_notes_users_UserId1
    PRINT 'Dropped FK_notes_users_UserId1'
END

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_tags_users_UserId1')
BEGIN
    ALTER TABLE tags DROP CONSTRAINT FK_tags_users_UserId1
    PRINT 'Dropped FK_tags_users_UserId1'
END

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_workspaces_users_UserId2')
BEGIN
    ALTER TABLE workspaces DROP CONSTRAINT FK_workspaces_users_UserId2
    PRINT 'Dropped FK_workspaces_users_UserId2'
END

-- Drop indexes
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_notes_UserId1' AND object_id = OBJECT_ID('notes'))
BEGIN
    DROP INDEX IX_notes_UserId1 ON notes
    PRINT 'Dropped index IX_notes_UserId1'
END

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_tags_UserId1' AND object_id = OBJECT_ID('tags'))
BEGIN
    DROP INDEX IX_tags_UserId1 ON tags
    PRINT 'Dropped index IX_tags_UserId1'
END

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_workspaces_UserId2' AND object_id = OBJECT_ID('workspaces'))
BEGIN
    DROP INDEX IX_workspaces_UserId2 ON workspaces
    PRINT 'Dropped index IX_workspaces_UserId2'
END

-- Drop duplicate columns
IF EXISTS (SELECT 1 FROM sys.columns WHERE name = 'UserId1' AND object_id = OBJECT_ID('notes'))
BEGIN
    ALTER TABLE notes DROP COLUMN UserId1
    PRINT 'Dropped column notes.UserId1'
END

IF EXISTS (SELECT 1 FROM sys.columns WHERE name = 'UserId1' AND object_id = OBJECT_ID('tags'))
BEGIN
    ALTER TABLE tags DROP COLUMN UserId1
    PRINT 'Dropped column tags.UserId1'
END

IF EXISTS (SELECT 1 FROM sys.columns WHERE name = 'UserId2' AND object_id = OBJECT_ID('workspaces'))
BEGIN
    ALTER TABLE workspaces DROP COLUMN UserId2
    PRINT 'Dropped column workspaces.UserId2'
END

PRINT 'Duplicate UserId columns cleanup completed successfully!'