namespace SuperAppModels.Models
{
    /// <summary>
    /// Folder entity (renamed from Tag)
    /// Folders are containers for organizing items in workspaces
    /// Can be shared across multiple workspaces
    /// </summary>
    public class Folder : ITimestampEntity
    {
        // Database columns - must match exactly with 'folders' table schema
        public int FolderId { get; set; } // PRIMARY KEY: folder_id
        public int UserId { get; set; } // FOREIGN KEY: user_id

        // Folder info
        public string Name { get; set; } = string.Empty; // name (255 chars)
        public string Slug { get; set; } = string.Empty; // slug (generated by application)
        public string? Color { get; set; } = "#3B82F6"; // color (hex format)
        public string? Icon { get; set; } // icon (50 chars)
        public string? Description { get; set; } // description (1000 chars)

        // Metadata
        public string? Metadata { get; set; } // metadata (JSON)
        public int UsageCount { get; set; } = 0; // usage_count (number of workspaces using this folder)

        // Timestamps (ITimestampEntity)
        public DateTime? CreatedAt { get; set; } // created_at
        public DateTime? UpdatedAt { get; set; } // updated_at
        public DateTime? DeletedAt { get; set; } // deleted_at (soft delete)

        // Navigation properties for EF Core
        public User User { get; set; } = null!;
        public ICollection<WorkspaceItem> WorkspaceItems { get; set; } = new List<WorkspaceItem>();
        public ICollection<EntityTag> EntityTags { get; set; } = new List<EntityTag>();

        public Folder()
        {
            CreatedAt = DateTime.UtcNow;
            UpdatedAt = DateTime.UtcNow;
            Color = "#3B82F6"; // Default blue color
            UsageCount = 0;
            Slug = string.Empty;
        }

        public Folder(string name, int userId) : this()
        {
            Name = name ?? throw new ArgumentNullException(nameof(name));
            UserId = userId;
            Slug = GenerateSlug(name);
        }

        /// <summary>
        /// Updates the folder content with validation and automatic timestamp management
        /// </summary>
        public void Update(string name, string? description = null, string? color = null, string? icon = null)
        {
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException("Name cannot be empty", nameof(name));

            Name = name;
            Description = description;
            if (color != null) Color = color;
            if (icon != null) Icon = icon;

            // Regenerate slug if name changed
            Slug = GenerateSlug(name);
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Increments usage count when folder is added to a workspace
        /// </summary>
        public void IncrementUsage()
        {
            UsageCount++;
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Decrements usage count when folder is removed from a workspace
        /// </summary>
        public void DecrementUsage()
        {
            if (UsageCount > 0)
            {
                UsageCount--;
                UpdatedAt = DateTime.UtcNow;
            }
        }

        /// <summary>
        /// Marks the folder as deleted with soft delete pattern
        /// </summary>
        public void SoftDelete()
        {
            DeletedAt = DateTime.UtcNow;
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Generates URL-friendly slug from name
        /// </summary>
        private static string GenerateSlug(string name)
        {
            return name.ToLowerInvariant()
                .Replace(" ", "-")
                .Replace("_", "-")
                // Remove special characters
                .Where(c => char.IsLetterOrDigit(c) || c == '-')
                .Aggregate(new System.Text.StringBuilder(), (sb, c) => sb.Append(c))
                .ToString();
        }
    }
}
