namespace SuperAppModels.Models
{
    public class Note : ITimestampEntity
    {
        // Database columns - must match exactly with 'notes' table schema
        public int NoteId { get; set; } // PRIMARY KEY: note_id
        public int UserId { get; set; } // FOREIGN KEY: user_id
        
        // Content
        public string Name { get; set; } = string.Empty; // name (200 chars)
        public string? Description { get; set; } // description (1000 chars)
        public string? Content { get; set; } // content (NVARCHAR(MAX) - Markdown)
        
        // URL routing
        public string? Slug { get; set; } // slug (auto-generated by trigger)
        
        // Display customization
        public string? Color { get; set; } // color (hex format #RRGGBB)
        public string? Icon { get; set; } // icon identifier
        
        // Status flags
        public bool IsArchived { get; set; } = false; // is_archived
        public bool IsPinned { get; set; } = false; // is_pinned
        public bool IsFavorite { get; set; } = false; // is_favorite
        
        // Metadata
        public int WordCount { get; set; } = 0; // word_count (auto-calculated)
        public int VersionCount { get; set; } = 1; // version_count (auto-incremented)
        
        // Timestamps (ITimestampEntity)
        public DateTime? CreatedAt { get; set; } // created_at
        public DateTime? UpdatedAt { get; set; } // updated_at
        public DateTime? DeletedAt { get; set; } // deleted_at (soft delete)
        
        // Navigation properties for EF Core
        public User User { get; set; } = null!;
        public ICollection<NoteMember> Members { get; set; } = new List<NoteMember>();
        public ICollection<NoteVersion> Versions { get; set; } = new List<NoteVersion>();

        public Note()
        {
            CreatedAt = DateTime.UtcNow;
            IsArchived = false;
            IsPinned = false;
            IsFavorite = false;
            WordCount = 0;
            VersionCount = 1;
        }

        public Note(string name, int userId) : this()
        {
            Name = name ?? throw new ArgumentNullException(nameof(name));
            UserId = userId;
        }

        /// <summary>
        /// Updates the note content with validation and automatic timestamp management
        /// </summary>
        public void UpdateContent(string name, string? description = null, string? content = null)
        {
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException("Name cannot be empty", nameof(name));

            Name = name;
            Description = description;
            Content = content;
            UpdatedAt = DateTime.UtcNow;
            
            // Update word count if content provided
            if (content != null)
            {
                WordCount = CountWords(content);
            }
        }

        /// <summary>
        /// Toggles the archive status
        /// </summary>
        public void ToggleArchive()
        {
            IsArchived = !IsArchived;
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Toggles the pinned status
        /// </summary>
        public void TogglePin()
        {
            IsPinned = !IsPinned;
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Toggles the favorite status
        /// </summary>
        public void ToggleFavorite()
        {
            IsFavorite = !IsFavorite;
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Simple word counting for content
        /// </summary>
        private static int CountWords(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
                return 0;
            
            return text.Split(new char[] { ' ', '\t', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries).Length;
        }
    }
}