namespace SuperAppModels.Models
{
    public class Tag : ITimestampEntity
    {
        // Database columns - must match exactly with 'tags' table schema
        public int TagId { get; set; } // PRIMARY KEY: tag_id
        public int UserId { get; set; } // FOREIGN KEY: user_id
        
        // Tag info
        public string Name { get; set; } = string.Empty; // name (255 chars)
        public string Slug { get; set; } = string.Empty; // slug (generated by trigger)
        public string? Color { get; set; } = "#3B82F6"; // color (hex format)
        public string? Icon { get; set; } // icon (50 chars)
        public string? Description { get; set; } // description (1000 chars)
        
        // Metadata
        public string? Metadata { get; set; } // metadata (JSON)
        public int UsageCount { get; set; } = 0; // usage_count
        
        // Timestamps (ITimestampEntity)
        public DateTime? CreatedAt { get; set; } // created_at
        public DateTime? UpdatedAt { get; set; } // updated_at
        public DateTime? DeletedAt { get; set; } // deleted_at (soft delete)
        
        // Navigation properties for EF Core
        public User User { get; set; } = null!;

        public Tag()
        {
            CreatedAt = DateTime.UtcNow;
            Color = "#3B82F6"; // Default blue color
            UsageCount = 0;
            Slug = string.Empty;
        }

        public Tag(string name, int userId) : this()
        {
            Name = name ?? throw new ArgumentNullException(nameof(name));
            UserId = userId;
        }

        /// <summary>
        /// Updates the tag content with validation and automatic timestamp management
        /// </summary>
        public void Update(string name, string? description = null, string? color = null, string? icon = null)
        {
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException("Name cannot be empty", nameof(name));

            Name = name;
            Description = description;
            if (color != null) Color = color;
            if (icon != null) Icon = icon;
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Increments usage count when tag is used
        /// </summary>
        public void IncrementUsage()
        {
            UsageCount++;
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Decrements usage count when tag is removed
        /// </summary>
        public void DecrementUsage()
        {
            if (UsageCount > 0)
            {
                UsageCount--;
                UpdatedAt = DateTime.UtcNow;
            }
        }

        /// <summary>
        /// Marks the tag as deleted with soft delete pattern
        /// </summary>
        public void SoftDelete()
        {
            DeletedAt = DateTime.UtcNow;
            UpdatedAt = DateTime.UtcNow;
        }
    }
}