<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Timeline\TimelineAPI.csproj" />
	  <PackageReference Include="DbDataReaderMapper" Version="1.2.0" />
	  <ProjectReference Include="..\TLModels\TLMos.csproj" />
	  <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

</Project>
