-- ============================================
-- FILE: procedures/tags/usp_i_tag.sql
-- PURPOSE: Create new tag
-- DEPENDENCIES: tags table
-- ============================================

PRINT '';
PRINT '📝 Creating procedure: usp_i_tag';
PRINT '   Purpose: Create new tag for user';
PRINT '';

GO
CREATE OR ALTER PROCEDURE usp_i_tag
    @user_id INT,
    @name NVARCHAR(255),
    @color NVARCHAR(7) = NULL,
    @icon NVARCHAR(50) = NULL,
    @description NVARCHAR(MAX) = NULL,
    @metadata NVARCHAR(MAX) = NULL,
    @tag_id INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    
    BEGIN TRY
        BEGIN TRANSACTION;
        
        -- Validate user exists
        IF NOT EXISTS (SELECT 1 FROM users WHERE id = @user_id AND deleted_at IS NULL)
        BEGIN
            RAISERROR('User not found', 16, 1);
            RETURN;
        END
        
        -- Check duplicate name
        IF EXISTS (
            SELECT 1 FROM tags
            WHERE user_id = @user_id
            AND name = @name
            AND deleted_at IS NULL
        )
        BEGIN
            RAISERROR('Tag with same name already exists', 16, 1);
            RETURN;
        END
        
        -- Generate slug (will be auto-generated by trigger, but we can set it)
        DECLARE @slug NVARCHAR(255);
        SET @slug = LOWER(REPLACE(@name, ' ', '-'));
        
        -- Make slug unique
        DECLARE @counter INT = 1;
        DECLARE @original_slug NVARCHAR(255) = @slug;
        WHILE EXISTS (
            SELECT 1 FROM tags 
            WHERE user_id = @user_id 
            AND slug = @slug 
            AND deleted_at IS NULL
        )
        BEGIN
            SET @slug = @original_slug + '-' + CAST(@counter AS NVARCHAR(10));
            SET @counter = @counter + 1;
        END
        
        -- Insert tag (flat structure, hierarchy in workspace_items)
        INSERT INTO tags (
            user_id,
            name,
            slug,
            color,
            icon,
            description,
            metadata,
            usage_count,
            created_at,
            updated_at
        )
        VALUES (
            @user_id,
            @name,
            @slug,
            @color,
            @icon,
            @description,
            @metadata,
            0, -- Initial usage count
            GETUTCDATE(),
            GETUTCDATE()
        );
        
        SET @tag_id = SCOPE_IDENTITY();
        
        COMMIT TRANSACTION;
        
        -- Return created tag
        SELECT 
            id,
            user_id,
            name,
            slug,
            color,
            icon,
            description,
            metadata,
            usage_count,
            created_at,
            updated_at
        FROM tags
        WHERE id = @tag_id;
        
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
            
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();
        
        RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END;
GO

PRINT '   ✅ usp_i_tag created';
GO
