// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperAppDataRepositories.Data;

#nullable disable

namespace SuperAppDataRepositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperAppModels.Models.EntityTag", b =>
                {
                    b.Property<long>("EntityTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("entity_tag_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EntityTagId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<int>("TaggedBy")
                        .HasColumnType("int")
                        .HasColumnName("tagged_by");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityTagId");

                    b.HasIndex("FolderId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_entity_tags_tag");

                    b.HasIndex("TaggedBy")
                        .HasDatabaseName("IX_entity_tags_user");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_entity_tags_entity");

                    b.HasIndex("TagId", "EntityType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("UQ_entity_tags_tag_entity")
                        .HasFilter("[deleted_at] IS NULL");

                    b.ToTable("entity_tags", "dbo");
                });

            modelBuilder.Entity("SuperAppModels.Models.EntityType", b =>
                {
                    b.Property<string>("TypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_name");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayPlural")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display_plural");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<bool>("SupportsSharing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_sharing");

                    b.Property<bool>("SupportsVersioning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_versioning");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("table_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("TypeName");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_entity_types_display_name");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_entity_types_enabled")
                        .HasFilter("[is_enabled] = 1");

                    b.ToTable("entity_types", "dbo");
                });

            modelBuilder.Entity("SuperAppModels.Models.FileInfo", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("download_count");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("extension");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_favorite");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<DateTime?>("LastDownloadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_downloaded_at");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("name");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("original_filename");

                    b.Property<string>("Slug")
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FileId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_files_created_at");

                    b.HasIndex("MimeType")
                        .HasDatabaseName("IX_files_mime_type");

                    b.HasIndex("Slug")
                        .HasDatabaseName("IX_files_slug");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_files_user_id");

                    b.ToTable("files", "dbo");
                });

            modelBuilder.Entity("SuperAppModels.Models.Folder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("folder_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FolderId"));

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#3B82F6")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FolderId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_folders_name");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("IX_folders_usage");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_folders_user");

                    b.HasIndex("UserId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_folders_user_slug")
                        .HasFilter("[deleted_at] IS NULL");

                    b.ToTable("folders", "dbo");
                });

            modelBuilder.Entity("SuperAppModels.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("note_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("color");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_favorite");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("VersionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("version_count");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("word_count");

                    b.HasKey("NoteId");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("IX_notes_is_archived");

                    b.HasIndex("IsFavorite")
                        .HasDatabaseName("IX_notes_is_favorite");

                    b.HasIndex("IsPinned")
                        .HasDatabaseName("IX_notes_is_pinned");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_notes_name");

                    b.HasIndex("Slug")
                        .HasDatabaseName("IX_notes_slug");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_notes_user_id");

                    b.ToTable("notes", "dbo");
                });

            modelBuilder.Entity("SuperAppModels.Models.NoteMember", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MemberId"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InvitationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("invitation_status");

                    b.Property<DateTime?>("InvitedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("invited_at");

                    b.Property<int?>("InvitedBy")
                        .HasColumnType("int")
                        .HasColumnName("invited_by");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_accessed_at");

                    b.Property<int>("NoteId")
                        .HasColumnType("int")
                        .HasColumnName("note_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("viewer")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MemberId");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("IX_note_members_invited_by");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("IX_note_members_note_id");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_note_members_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_note_members_user_id");

                    b.HasIndex("NoteId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_note_members_note_user");

                    b.ToTable("note_members", "dbo");
                });

            modelBuilder.Entity("SuperAppModels.Models.NoteVersion", b =>
                {
                    b.Property<long>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("version_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VersionId"));

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("change_summary");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("name");

                    b.Property<int>("NoteId")
                        .HasColumnType("int")
                        .HasColumnName("note_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int")
                        .HasColumnName("version_number");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("word_count");

                    b.HasKey("VersionId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_note_versions_created_at");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_note_versions_created_by");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("IX_note_versions_note_id");

                    b.HasIndex("NoteId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_note_versions_note_version");

                    b.ToTable("note_versions", "dbo");
                });

            modelBuilder.Entity("SuperAppModels.Models.StandardRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_standard_registry_active")
                        .HasFilter("active = 1");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_standard_registry_code");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_standard_registry_type");

                    b.HasIndex("Type", "Code")
                        .HasDatabaseName("ix_standard_registry_type_code");

                    b.ToTable("standard_registry", "dbo");
                });

            modelBuilder.Entity("SuperAppModels.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#3B82F6")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TagId");

                    b.HasIndex("UserId", "DeletedAt")
                        .HasDatabaseName("IX_tags_new_user")
                        .HasFilter("[deleted_at] IS NULL");

                    b.HasIndex("UserId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_tags_new_user_slug")
                        .HasFilter("[deleted_at] IS NULL");

                    b.HasIndex("UserId", "UsageCount")
                        .HasDatabaseName("IX_tags_new_usage")
                        .HasFilter("[deleted_at] IS NULL");

                    b.ToTable("tags_new", "dbo");
                });

            modelBuilder.Entity("SuperAppModels.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Preferences")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preferences");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email")
                        .HasFilter("[deleted_at] IS NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_users_is_active")
                        .HasFilter("[deleted_at] IS NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_users_username")
                        .HasFilter("[deleted_at] IS NULL");

                    b.ToTable("users", "urm");
                });

            modelBuilder.Entity("SuperAppModels.Models.UserProfile", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("AppC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("app_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("IsUpdatedTodays")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("is_updated_todays");

                    b.Property<string>("Parents")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parents");

                    b.Property<string>("Priorities")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("priorities");

                    b.Property<string>("RepeatTypes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("repeat_types");

                    b.Property<string>("Statuses")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("statuses");

                    b.Property<string>("Types")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("types");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Email");

                    b.HasIndex("AppC")
                        .HasDatabaseName("IX_user_profiles_app_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_user_profiles_is_active");

                    b.ToTable("user_profiles", "urm");
                });

            modelBuilder.Entity("SuperAppModels.Models.Workspace", b =>
                {
                    b.Property<int>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("workspace_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkspaceId"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<bool>("IsTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_template");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_accessed_at");

                    b.Property<int>("MaxDepth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("max_depth");

                    b.Property<int>("MemberCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("member_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("RelationshipCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("relationship_count");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("settings");

                    b.Property<int>("TagCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("tag_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("hierarchy")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("WorkspaceId");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("IX_workspaces_is_default")
                        .HasFilter("[is_default] = 1 AND [deleted_at] IS NULL");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("IX_workspaces_is_public")
                        .HasFilter("[is_public] = 1 AND [deleted_at] IS NULL");

                    b.HasIndex("LastAccessedAt")
                        .HasDatabaseName("IX_workspaces_last_accessed");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_workspaces_name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_workspaces_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_workspaces_user");

                    b.ToTable("workspaces", "ws");
                });

            modelBuilder.Entity("SuperAppModels.Models.WorkspaceItem", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemId"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int")
                        .HasColumnName("added_by");

                    b.Property<int>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("child_id");

                    b.Property<int?>("ChildNoteNoteId")
                        .HasColumnType("int");

                    b.Property<int?>("ChildTagTagId")
                        .HasColumnType("int");

                    b.Property<string>("ChildType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("child_type");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Depth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("depth");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<string>("ItemPath")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("item_path");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("label");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<int?>("ParentTagId")
                        .HasColumnType("int")
                        .HasColumnName("parent_tag_id");

                    b.Property<string>("RelationshipType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("relationship_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int")
                        .HasColumnName("workspace_id");

                    b.HasKey("ItemId");

                    b.HasIndex("AddedBy");

                    b.HasIndex("ChildNoteNoteId");

                    b.HasIndex("ChildTagTagId");

                    b.HasIndex("FolderId");

                    b.HasIndex("ItemPath")
                        .HasDatabaseName("IX_workspace_items_path");

                    b.HasIndex("ParentTagId")
                        .HasDatabaseName("IX_workspace_items_parent");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_workspace_items_workspace");

                    b.HasIndex("ChildType", "ChildId")
                        .HasDatabaseName("IX_workspace_items_child");

                    b.HasIndex("WorkspaceId", "ParentTagId")
                        .HasDatabaseName("IX_workspace_items_workspace_parent");

                    b.HasIndex("WorkspaceId", "ParentTagId", "ChildType", "ChildId")
                        .IsUnique()
                        .HasDatabaseName("UQ_workspace_items_unique")
                        .HasFilter("[deleted_at] IS NULL");

                    b.ToTable("workspace_items", "ws");
                });

            modelBuilder.Entity("SuperAppModels.Models.WorkspaceMember", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MemberId"));

                    b.Property<string>("CustomPermissions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("custom_permissions");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InvitationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("invitation_status");

                    b.Property<DateTime?>("InvitedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("invited_at");

                    b.Property<int?>("InvitedBy")
                        .HasColumnType("int")
                        .HasColumnName("invited_by");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_accessed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("viewer")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int")
                        .HasColumnName("workspace_id");

                    b.HasKey("MemberId");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_workspace_members_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_workspace_members_user");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_workspace_members_workspace");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_workspace_members_unique")
                        .HasFilter("[deleted_at] IS NULL");

                    b.ToTable("workspace_members", "ws");
                });

            modelBuilder.Entity("SuperAppModels.Models.WorkspaceRelationshipType", b =>
                {
                    b.Property<int>("RelationshipTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("relationship_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationshipTypeId"));

                    b.Property<bool>("AllowsCycles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("allows_cycles");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsBidirectional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bidirectional");

                    b.Property<string>("LineStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("solid")
                        .HasColumnName("line_style");

                    b.Property<int>("LineWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("line_width");

                    b.Property<int?>("MaxDepth")
                        .HasColumnType("int")
                        .HasColumnName("max_depth");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("validation_rules");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int")
                        .HasColumnName("workspace_id");

                    b.HasKey("RelationshipTypeId");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_workspace_relationship_types_sort_order");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_workspace_relationship_types_workspace");

                    b.HasIndex("WorkspaceId", "TypeName")
                        .IsUnique()
                        .HasDatabaseName("UQ_workspace_relationship_types_unique")
                        .HasFilter("[deleted_at] IS NULL");

                    b.ToTable("workspace_relationship_types", "ws");
                });

            modelBuilder.Entity("SuperAppModels.Models.EntityTag", b =>
                {
                    b.HasOne("SuperAppModels.Models.Folder", null)
                        .WithMany("EntityTags")
                        .HasForeignKey("FolderId");

                    b.HasOne("SuperAppModels.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperAppModels.Models.User", "TaggedByUser")
                        .WithMany()
                        .HasForeignKey("TaggedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TaggedByUser");
                });

            modelBuilder.Entity("SuperAppModels.Models.FileInfo", b =>
                {
                    b.HasOne("SuperAppModels.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuperAppModels.Models.Folder", b =>
                {
                    b.HasOne("SuperAppModels.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuperAppModels.Models.Note", b =>
                {
                    b.HasOne("SuperAppModels.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_notes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuperAppModels.Models.NoteMember", b =>
                {
                    b.HasOne("SuperAppModels.Models.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_note_members_users_invited_by");

                    b.HasOne("SuperAppModels.Models.Note", "Note")
                        .WithMany("Members")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperAppModels.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_note_members_users_user_id");

                    b.Navigation("Inviter");

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuperAppModels.Models.NoteVersion", b =>
                {
                    b.HasOne("SuperAppModels.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_note_versions_users_created_by");

                    b.HasOne("SuperAppModels.Models.Note", "Note")
                        .WithMany("Versions")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("SuperAppModels.Models.Tag", b =>
                {
                    b.HasOne("SuperAppModels.Models.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuperAppModels.Models.Workspace", b =>
                {
                    b.HasOne("SuperAppModels.Models.User", "User")
                        .WithMany("Workspaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuperAppModels.Models.WorkspaceItem", b =>
                {
                    b.HasOne("SuperAppModels.Models.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperAppModels.Models.Note", "ChildNote")
                        .WithMany()
                        .HasForeignKey("ChildNoteNoteId");

                    b.HasOne("SuperAppModels.Models.Tag", "ChildTag")
                        .WithMany()
                        .HasForeignKey("ChildTagTagId");

                    b.HasOne("SuperAppModels.Models.Folder", null)
                        .WithMany("WorkspaceItems")
                        .HasForeignKey("FolderId");

                    b.HasOne("SuperAppModels.Models.Tag", "ParentTag")
                        .WithMany()
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SuperAppModels.Models.Workspace", "Workspace")
                        .WithMany("Items")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("ChildNote");

                    b.Navigation("ChildTag");

                    b.Navigation("ParentTag");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("SuperAppModels.Models.WorkspaceMember", b =>
                {
                    b.HasOne("SuperAppModels.Models.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SuperAppModels.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperAppModels.Models.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inviter");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("SuperAppModels.Models.WorkspaceRelationshipType", b =>
                {
                    b.HasOne("SuperAppModels.Models.Workspace", "Workspace")
                        .WithMany("RelationshipTypes")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("SuperAppModels.Models.Folder", b =>
                {
                    b.Navigation("EntityTags");

                    b.Navigation("WorkspaceItems");
                });

            modelBuilder.Entity("SuperAppModels.Models.Note", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SuperAppModels.Models.User", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Tags");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("SuperAppModels.Models.Workspace", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Members");

                    b.Navigation("RelationshipTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
