using AutoMapper;
using SuperAppModels.DTOs.Requests;
using SuperAppModels.DTOs.Responses;
using SuperAppModels.Models;

namespace SuperAppServices.Mappings
{
    /// <summary>
    /// AutoMapper profile for mapping between Models and DTOs
    /// </summary>
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // Note mappings
            CreateMap<Note, NoteDTO>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)) // Map Id -> Id
                .ForMember(dest => dest.Tags, opt => opt.Ignore()); // Tags will be set separately if needed

            CreateMap<CreateNoteRequest, Note>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            CreateMap<UpdateNoteRequest, Note>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            CreateMap<UpsertNoteRequest, Note>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // Folder mappings (NEW - ws.folders schema)
            CreateMap<Folder, FolderResponse>();

            // Folder mappings (Workspace/Tag - OLD)
            CreateMap<Tag, FolderResponse>();
            CreateMap<Tag, TagDto>();
            CreateMap<Tag, TagMetadata>();

            CreateMap<UpsertFolderRequest, Tag>()
                .ForMember(dest => dest.TagId, opt => opt.Ignore())
                .ForMember(dest => dest.Slug, opt => opt.Ignore()) // Generated by DB trigger
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UsageCount, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            CreateMap<UpdateFolderRequest, Tag>()
                .ForMember(dest => dest.TagId, opt => opt.Ignore())
                .ForMember(dest => dest.Slug, opt => opt.Ignore()) // Generated by DB trigger
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.UsageCount, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // User mappings
            CreateMap<User, UserResponse>();
            CreateMap<UserProfile, UserProfileResponse>();
            CreateMap<UpdateUserProfileRequest, UserProfile>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());

            // Workspace mappings
            CreateMap<Workspace, WsResponse>();
            CreateMap<Workspace, WorkspaceDTO>();
            CreateMap<UpsertWorkspaceRequest, Workspace>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore())
                .ForMember(dest => dest.Items, opt => opt.Ignore());

            // WorkspaceItem mappings (tree view model -> response DTO)
            CreateMap<WorkspaceItem, WorkspaceItemResponse>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.ItemId)) // Entity ID
                .ForMember(dest => dest.RelationshipId, opt => opt.MapFrom(src => src.RelationshipId)) // Relationship ID
                .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Type)) // Type
                .ForMember(dest => dest.SortOrder, opt => opt.MapFrom(src => src.Position))
                .ForMember(dest => dest.Depth, opt => opt.MapFrom(src => src.Level))
                .ForMember(dest => dest.Metadata, opt => opt.Ignore())
                .ForMember(dest => dest.Children, opt => opt.Ignore())
                .ForMember(dest => dest.IsExpanded, opt => opt.Ignore())
                .ForMember(dest => dest.IsSelected, opt => opt.Ignore());

            // StandardRegistry mappings
            CreateMap<StandardRegistry, StandardRegistryResponse>();
            CreateMap<StandardRegistryRequest, StandardRegistry>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());
        }
    }
}
